//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KisanWeighningEntities : DbContext
    {
        public KisanWeighningEntities()
            : base("name=KisanWeighningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BankDetailsPerPurchase> tbl_BankDetailsPerPurchase { get; set; }
        public virtual DbSet<tbl_BrokerMaster> tbl_BrokerMaster { get; set; }
        public virtual DbSet<tbl_CashCreditMaster> tbl_CashCreditMaster { get; set; }
        public virtual DbSet<tbl_CashReceipt> tbl_CashReceipt { get; set; }
        public virtual DbSet<tbl_categoryMaster> tbl_categoryMaster { get; set; }
        public virtual DbSet<tbl_DealerMaster> tbl_DealerMaster { get; set; }
        public virtual DbSet<tbl_ExpensesMaster> tbl_ExpensesMaster { get; set; }
        public virtual DbSet<tbl_ExpensesPurposeMaster> tbl_ExpensesPurposeMaster { get; set; }
        public virtual DbSet<tbl_farmer_dealer_Mapping> tbl_farmer_dealer_Mapping { get; set; }
        public virtual DbSet<tbl_FarmerMaster> tbl_FarmerMaster { get; set; }
        public virtual DbSet<tbl_MasterMenuName> tbl_MasterMenuName { get; set; }
        public virtual DbSet<tbl_MenuMaster> tbl_MenuMaster { get; set; }
        public virtual DbSet<tbl_PaymentType> tbl_PaymentType { get; set; }
        public virtual DbSet<tbl_pool_MachineData_Purchase> tbl_pool_MachineData_Purchase { get; set; }
        public virtual DbSet<tbl_productMaster> tbl_productMaster { get; set; }
        public virtual DbSet<tbl_ProductTaxEntry> tbl_ProductTaxEntry { get; set; }
        public virtual DbSet<tbl_PurchaseEntry_Master> tbl_PurchaseEntry_Master { get; set; }
        public virtual DbSet<tbl_PurchaseEntry_Master_Payment> tbl_PurchaseEntry_Master_Payment { get; set; }
        public virtual DbSet<tbl_PurchaseOutStanding> tbl_PurchaseOutStanding { get; set; }
        public virtual DbSet<tbl_PurchseStockMaster> tbl_PurchseStockMaster { get; set; }
        public virtual DbSet<tbl_RemoteConnection> tbl_RemoteConnection { get; set; }
        public virtual DbSet<tbl_SalesEntry_Master> tbl_SalesEntry_Master { get; set; }
        public virtual DbSet<tbl_SalesEntry_Master_Payment> tbl_SalesEntry_Master_Payment { get; set; }
        public virtual DbSet<tbl_SalesOutStanding> tbl_SalesOutStanding { get; set; }
        public virtual DbSet<tbl_salesPartyRegistartion> tbl_salesPartyRegistartion { get; set; }
        public virtual DbSet<tbl_SalesSockMaster> tbl_SalesSockMaster { get; set; }
        public virtual DbSet<tbl_TaxMaster> tbl_TaxMaster { get; set; }
        public virtual DbSet<tbl_TransportMaster> tbl_TransportMaster { get; set; }
        public virtual DbSet<tbl_truck_Transport_Mapping> tbl_truck_Transport_Mapping { get; set; }
        public virtual DbSet<tbl_truckMaster> tbl_truckMaster { get; set; }
        public virtual DbSet<tbl_UserDetails> tbl_UserDetails { get; set; }
    }
}
