//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashReceipt
    {
        public int pkid { get; set; }
        public string personname { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> cashAmt { get; set; }
        public string sourcename { get; set; }
        public Nullable<System.DateTime> currentdate { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> payment_fkid { get; set; }
    }
}
