//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pool_MachineData_Purchase
    {
        public int pkid { get; set; }
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> ticketdate { get; set; }
        public Nullable<int> farmerid { get; set; }
        public string truckRFID { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public Nullable<System.DateTime> outtime { get; set; }
        public Nullable<int> producttypeid { get; set; }
        public Nullable<decimal> Grossweight { get; set; }
        public Nullable<decimal> TairWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<long> machine_fkid { get; set; }
        public string transportname { get; set; }
        public string challanno { get; set; }
        public Nullable<decimal> challanweight { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public string field3 { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> weighningcharges { get; set; }
        public Nullable<int> invoicestatus { get; set; }
    }
}
