//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDetails
    {
        public int pkid { get; set; }
        public string User_fkid { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string mobileno { get; set; }
        public string emailid { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> department { get; set; }
    }
}
