//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesSockMaster
    {
        public int pkid { get; set; }
        public Nullable<int> stock_fkid { get; set; }
        public Nullable<decimal> produceCottonbells { get; set; }
        public Nullable<decimal> produceCottonSeed { get; set; }
        public Nullable<decimal> totalStock { get; set; }
        public Nullable<decimal> produceTotalStock { get; set; }
        public Nullable<decimal> balancestock { get; set; }
        public Nullable<System.DateTime> lastmodifieddate { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<int> cid { get; set; }
        public string mdata { get; set; }
    }
}
