//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashCreditMaster
    {
        public int pkid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> purchaseorsale { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> invoiceidorexpensid { get; set; }
        public Nullable<System.DateTime> currentdatetime { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
        public Nullable<int> payment_fkid { get; set; }
    }
}
