//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseEntry_Master
    {
        public int pkid { get; set; }
        public Nullable<int> purchasemachine_fkid { get; set; }
        public string drivername { get; set; }
        public string farmermobileno { get; set; }
        public string drivermobileno { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> qunatity { get; set; }
        public Nullable<decimal> RTGSCharges { get; set; }
        public Nullable<decimal> kata { get; set; }
        public Nullable<decimal> unloading { get; set; }
        public Nullable<decimal> bankcharges { get; set; }
        public Nullable<decimal> CD_dalali { get; set; }
        public Nullable<decimal> totaldeduction { get; set; }
        public Nullable<decimal> advance { get; set; }
        public Nullable<decimal> bhada { get; set; }
        public Nullable<decimal> loadingcharges { get; set; }
        public Nullable<decimal> netpayable_amt { get; set; }
        public Nullable<decimal> cd { get; set; }
        public Nullable<decimal> mapai { get; set; }
        public string advance_remark { get; set; }
        public Nullable<int> Dealer_fkid { get; set; }
        public Nullable<System.DateTime> currentdatetime { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> paymentdays { get; set; }
        public string VillageName { get; set; }
        public Nullable<int> stockread { get; set; }
        public string fname { get; set; }
    }
}
