//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_salesPartyRegistartion
    {
        public int pkid { get; set; }
        public Nullable<int> Sale_fkid { get; set; }
        public string partyname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string mobileno { get; set; }
        public string emailid { get; set; }
        public string GSTNo { get; set; }
        public Nullable<System.DateTime> Partyregdate { get; set; }
        public string city { get; set; }
    }
}
