//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_truckMaster
    {
        public int pkid { get; set; }
        public string RFIDnumber { get; set; }
        public string truckno { get; set; }
        public Nullable<decimal> tairweight { get; set; }
        public Nullable<decimal> capcity { get; set; }
        public string trucktype { get; set; }
        public Nullable<int> salespurchase { get; set; }
    }
}
