//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankDetailsPerPurchase
    {
        public int pkid { get; set; }
        public Nullable<int> purchase_fkid { get; set; }
        public string Bank_name { get; set; }
        public string Branchname { get; set; }
        public string AccountHolder { get; set; }
        public string Accountno { get; set; }
        public string Ifsccode { get; set; }
        public string Cheq_Partyname { get; set; }
    }
}
