//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_truck_Transport_Mapping
    {
        public int pkid { get; set; }
        public Nullable<int> truckid { get; set; }
        public Nullable<int> transportid { get; set; }
        public string mappingRFID { get; set; }
    }
}
