//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesOutStanding
    {
        public int pkid { get; set; }
        public Nullable<int> partyid { get; set; }
        public Nullable<int> brokerid { get; set; }
        public Nullable<decimal> outAmt { get; set; }
        public Nullable<decimal> payingamt { get; set; }
        public string CheqPartyname { get; set; }
        public Nullable<decimal> CheqAmt { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<decimal> RTGSAMT { get; set; }
        public string CashPartyName { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Accountno { get; set; }
        public string IFSC { get; set; }
        public Nullable<System.DateTime> SystDate { get; set; }
        public Nullable<int> Payment_Method { get; set; }
        public string CHequeno { get; set; }
        public string Accoun_holder { get; set; }
        public string Details { get; set; }
        public Nullable<int> statusa { get; set; }
    }
}
