//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseEntry_Master_Payment
    {
        public int pkid { get; set; }
        public Nullable<int> Purchase_fkid { get; set; }
        public Nullable<int> invoice_fkid { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> RtgsDetail_fkid { get; set; }
        public Nullable<decimal> RTGSAmtPaying { get; set; }
        public Nullable<decimal> ChequeAmtpaying { get; set; }
        public string chequ_No { get; set; }
        public Nullable<int> cheqDetail_fkid { get; set; }
        public string CashPaidTO { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<decimal> pendingAmt { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> returnFlag { get; set; }
        public Nullable<decimal> returnAmt { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<decimal> Currentopeningbalance { get; set; }
        public Nullable<System.DateTime> ClearingDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> sendtobank { get; set; }
        public string DetailsTransaction { get; set; }
        public Nullable<int> OutstandingStatus { get; set; }
    }
}
