//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MenuMaster
    {
        public int pkid { get; set; }
        public Nullable<int> master_id { get; set; }
        public string MenuName { get; set; }
        public string manulink { get; set; }
        public Nullable<int> allowrole { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
