//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductTaxEntry
    {
        public int pkid { get; set; }
        public Nullable<int> Product_fkid { get; set; }
        public string HSNno { get; set; }
        public Nullable<int> tax_fkid { get; set; }
    }
}
