//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.KisanModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExpensesMaster
    {
        public int pkid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> purposeid { get; set; }
        public string personname { get; set; }
        public Nullable<int> Payment_type { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<int> Pay_Infofkid { get; set; }
        public string remark { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
